language: php

php:
    - 5.4
    - 5.5

before_script:
    - wget http://getcomposer.org/composer.phar
    - php composer.phar install --dev

script: phpunit --coverage-text --exclude-group ProcessTitle

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./build/coverage.clover